config/routes.rb
Rails.application.routes.draw do

  root to: 'landing_page#index'

  namespace :guest do
    get '/auth/login', to: 'guests#index', as: 'auth_login'
    post '/access-account', to: 'guests#access_account'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    post 'auth/sign_out', to: 'home#sign_out', as: 'sign_out'

    # users
    get '/user/edit', to: 'users#edit', as: 'user_edit'
    post '/user/update', to: 'users#update', as: 'user_update'
    post '/user/become_artist', to: 'users#convert_user_to_artist', as: 'convert_user_to_artist'

    get '/proposals', to: 'proposals#index', as: 'proposals'
    get '/proposals/new', to: 'proposals#new', as: 'new_proposals'

    post '/proposals/create', to: 'proposals#create', as: 'create_proposals'
    get '/proposals/edit/:id', to: 'proposals#edit', as: 'edit_proposals'
    post '/proposals/update', to: 'proposals#update', as: 'update_proposals'

    get '/musics', to: 'musics#index', as: 'musics'
    get '/musics/new', to: 'musics#new', as: 'new_music'
    post '/musics/create', to: 'musics#create', as: 'create_music'
    get '/musics/edit/:id', to: 'musics#edit', as: 'edit_music'
    post '/musics/update', to: 'musics#update', as: 'update_music'

    get '/goals', to: 'goals#index', as: 'goals'
    get '/goals/new', to: 'goals#new', as: 'new_goal'
    get '/goals/edit/:id', to: 'goals#edit', as: 'edit_goal'
    post '/goals/create', to: 'goals#create', as: 'create_goal'
    post '/goals/update', to: 'goals#update', as: 'update_goal'
  end

end

app/controllers/dashboard/goals_controller.rb
class Dashboard::GoalsController < ApplicationController

  def index
    begin
      goal_service = Firebase::Firestore::GoalService.new(user_id: current_user[:id])
      goals = goal_service.load_all_goals

      @goals = goals[:goals]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      goal_service = Firebase::Firestore::GoalService.new(allowed_parameters)
      goal_service.process_creation

      flash[:success] = I18n.t('dashboard.goals.success.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_goals_url
  end

  def edit
    begin
      params_proposal = { goal_id: params[:id], user_id: current_user[:id] }
      goal_service = Firebase::Firestore::GoalService.new(params_proposal)
      @goal = goal_service.load_goal
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      goal_service = Firebase::Firestore::GoalService.new(allowed_parameters)
      goal_service.process_update

      flash[:success] = I18n.t('dashboard.goals.success.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_goals_url
  end

  private

  def filter_params
    params.permit(:price, :description, :goal_id)
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      goal_service = Firebase::Firestore::GoalService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      goals = goal_service.load_all_goals

      @goals = goals[:goals]
      @albuns = all_songs[:albuns]
      @singles = all_songs[:singles]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def sign_out
    reset_session

    redirect_to guest_auth_login_path
  end

end

app/controllers/dashboard/musics_controller.rb
class Dashboard::MusicsController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      @singles = all_songs[:singles]
      @albuns = all_songs[:albuns]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_creation

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  def edit
    begin
      music_params = { music_id: params[:id], user_id: current_user[:id] }
      music_service = Firebase::Firestore::MusicService.new(music_params)
      @song = music_service.load_song

      flash[:warning] = I18n.t('dashboard.musics.messages.alert_edit_music')
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_update

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  private

  def filter_params
    params.permit(:music_title, :music_file, :number_track, :image_cover, :music_id)
  end

end

app/controllers/dashboard/proposals_controller.rb
class Dashboard::ProposalsController < ApplicationController

  def index
    begin
      proposal_service = Firebase::Firestore::ProposalService.new(user_id: current_user[:id])
      @all_proposals = proposal_service.load_all_proposals
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_creation

      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  def edit
    begin
      params_proposal = { proposal_id: params[:id], user_id: current_user[:id] }
      proposal_service = Firebase::Firestore::ProposalService.new(params_proposal)
      @proposal = proposal_service.load_proposal
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_update
      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  private

  def filter_params
    params.permit(:proposal_name, :price, :description, :proposal_id, :proposal_image)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  def edit
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.update_user
      flash[:success] = I18n.t('dashboard.users.messages.success.update_success')
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_user_edit_url
  end

  def convert_user_to_artist
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.transform_listener_in_artist
      flash[:success] = I18n.t('dashboard.users.messages.success.welcome_artist', user_name: current_user[:name])
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_url
  end

  private

  def filter_params
    params.permit(:username, :email, :complete_name, :phone_number, :select_gender,
                  :facebook_link, :instagram_link, :twitter_link, :city, :state, :about_me)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/dashboard/goals/_goals.html.erb
<tbody id="tbody-goals">

<% goals.each do |goal| %>

  <tr>
    <th scope="row">
      <div class="media align-items-center">
        <div class="media-body">
          <span class="mb-0 text-sm pl-3">
            <%= number_to_currency_br goal.data[:price] %>
          </span>
        </div>
      </div>
    </th>
    <td>
      <div class="media align-items-center">
        <div class="media-body text-left">
            <span class="mb-0 text-sm text-overflow">
              <%= goal.data[:description] %>
            </span>
        </div>
      </div>
    </td>
    <td class="text-right">
      <div class="dropdown">
        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" x-placement="bottom-end" style="position: absolute; transform: translate3d(-160px, 31px, 0px); top: 0px; left: 0px; will-change: transform;">
          <a class="dropdown-item" href="<%= dashboard_edit_goal_path(goal.document_id) %>">
            <%= I18n.t('dashboard.goals.buttons.edit') %>
          </a>
        </div>
      </div>
    </td>
  </tr>
<% end %>
</tbody>

app/views/dashboard/goals/edit.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Aqui você poderá editar a sua meta, ela será exibida no seu perfil do Voyce.',
      title: 'Meta do Usuário',
      css_class: 'col-lg-8 col-8'
  } %>

  <div class="d-flex">
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center text-uppercase">
            <div class="col-8">
              <h3 class="mb-0">
                <%= I18n.t('dashboard.goals.title.edit_goal') %>
              </h3>
            </div>
            <div class="col-4 text-right">
              <a href="<%= dashboard_goals_url %>" class="btn btn-link text-warning text-right">
                <%= I18n.t('dashboard.musics.buttons.back') %>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <h6 class="heading-small text-muted mb-4">
            <%= I18n.t('dashboard.goals.title.goals_informations') %>
          </h6>

          <%= form_tag dashboard_update_goal_path, :id => 'form-action' do %>

            <%= hidden_field_tag :goal_id, @goal.document_id %>

            <div class="row pl-lg-2 pr-lg-2">
              <div class="col-12">
                <div class="form-group d-flex flex-row mb-2">
                  <label class="w-25 mr-3">
                    <div class="h4 font-weight-600 mb-1">
                      <%= I18n.t('dashboard.proposals.fields.price') %>
                    </div>
                    <div class="h6 font-weight-300">
                      <%= I18n.t('dashboard.proposals.fields.required') %>
                    </div>
                  </label>
                  <div class="input-group mb-4">
                    <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fas fa-money-bill-wave"></i>
                  </span>
                    </div>
                    <input class="form-control money2"
                           name="price"
                           id="price"
                           placeholder="1000,00"
                           value="<%= @goal.data[:price] %>"
                           type="number"
                           min="0.00"
                           max="10000.00"
                           step="0.01" required>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group d-flex flex-row mb-2">
                  <label class="w-25 mr-3">
                    <h4 class="h4 font-weight-600 mb-1">
                      <%= I18n.t('dashboard.proposals.fields.description') %>
                    </h4>
                    <h4 class="h6 font-weight-300">
                      <%= I18n.t('dashboard.proposals.fields.required') %>
                    </h4>
                  </label>
                  <div class="input-group mb-4">
                      <textarea class="form-control form-control-alternative"
                                name="description"
                                id="description"
                                rows="4"
                                cols="80"
                                placeholder="Escreva aqui o que você planeja fazer com o dinheiro acumulado..."><%= @goal.data[:description] %></textarea>
                  </div>
                </div>
              </div>
              <div class="col-12 d-flex justify-content-end">
                <button type="submit" class="btn btn-success w-25" id="button-action">
                  <%= I18n.t('dashboard.goals.buttons.save') %>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xl-4 order-xl-1">
      <div class="card shadow shadow-lg--hover p-4">
        <%= image_tag('money-bag.svg', class: 'card-img-top') %>
      </div>
    </div>
  </div>

  <%= render 'dashboard/partials_shared/footer' %>

</div>

app/views/dashboard/goals/index.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Aqui você pode criar e visualizar suas Metas.',
      title: 'Gerencie suas metas',
      css_class: 'col-lg-12 col-12'
  } %>

  <div class="container-fluid">

    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col-8 text-uppercase">
                <h3 class="mb-0">
                  <%= I18n.t('dashboard.goals.title.goals') %>
                </h3>
              </div>
              <div class="col-4 text-right">
                <a href="<%= dashboard_new_goal_path %>" class="btn btn-1 btn-outline-success">
                  <%= I18n.t('dashboard.goals.buttons.create') %>
                </a>
              </div>
            </div>
          </div>

          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="pl-6" style="width: 10vw;"><%= I18n.t('dashboard.goals.fields.goal_value') %></th>
                <th scope="col" style="width: 50vw;"><%= I18n.t('dashboard.goals.fields.description') %></th>
                <th scope="col" style="width: 5vw;"></th>
              </tr>
            </thead>

            <% if @goals.present? && @goals.first.present? %>
              <%= render partial: 'dashboard/goals/goals', locals: { goals: @goals } %>
            <% else %>
              <tbody>
              <tr>
                <th scope="row">
                  <div class="media align-items-center mt-3">
                    <div class="media-body">
                        <span class="mb-0 text-sm">
                          <%= I18n.t('dashboard.goals.fields.no_meta') %>
                        </span>
                    </div>
                  </div>
                </th>
              </tr>
              </tbody>
            <% end %>
          </table>

          <!-- Pagination -->
          <div class="card-footer py-4">
            <nav class="d-flex justify-content-end" aria-label="...">

            </nav>
          </div>
        </div>
      </div>
    </div>

    <%= render 'dashboard/partials_shared/footer' %>

  </div>

</div>

app/views/dashboard/goals/new.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Aqui você poderá inserir a sua meta, ela será exibida no seu perfil do Voyce.',
      title: 'Meta do Usuário',
      css_class: 'col-lg-8 col-8'
  } %>

  <div class="d-flex">
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center text-uppercase">
            <div class="col-8">
              <h3 class="mb-0">
                <%= I18n.t('dashboard.goals.title.create_goal') %>
              </h3>
            </div>
            <div class="col-4 text-right">
              <a href="<%= dashboard_goals_url %>" class="btn btn-link text-warning text-right">
                <%= I18n.t('dashboard.musics.buttons.back') %>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <h6 class="heading-small text-muted mb-4">
            <%= I18n.t('dashboard.goals.title.goals_informations') %>
          </h6>

          <%= form_tag dashboard_create_goal_path, :id => 'form-action' do %>
            <div class="row pl-lg-2 pr-lg-2">
              <div class="col-12">
                <div class="form-group d-flex flex-row mb-2">
                  <label class="w-25 mr-3">
                    <div class="h4 font-weight-600 mb-1">
                      <%= I18n.t('dashboard.proposals.fields.price') %>
                    </div>
                    <div class="h6 font-weight-300">
                      <%= I18n.t('dashboard.proposals.fields.required') %>
                    </div>
                  </label>
                  <div class="input-group mb-4">
                    <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fas fa-money-bill-wave"></i>
                  </span>
                    </div>
                    <input class="form-control money2"
                           name="price"
                           id="price"
                           placeholder="1000,00"
                           type="number"
                           min="0.00"
                           max="10000.00"
                           required>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group d-flex flex-row mb-2">
                  <label class="w-25 mr-3">
                    <h4 class="h4 font-weight-600 mb-1">
                      <%= I18n.t('dashboard.proposals.fields.description') %>
                    </h4>
                    <h4 class="h6 font-weight-300">
                      <%= I18n.t('dashboard.proposals.fields.required') %>
                    </h4>
                  </label>
                  <div class="input-group mb-4">
                      <textarea class="form-control form-control-alternative"
                                name="description"
                                id="description"
                                rows="4"
                                cols="80"
                                placeholder="Escreva aqui o que você planeja fazer com o dinheiro acumulado..."></textarea>
                  </div>
                </div>
              </div>
              <div class="col-12 d-flex justify-content-end">
                <button type="submit" class="btn btn-success w-25" id="button-action">
                  <%= I18n.t('dashboard.goals.buttons.create') %>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xl-4 order-xl-1">
      <div class="card shadow shadow-lg--hover p-4">
        <%= image_tag('money-bag.svg', class: 'card-img-top') %>
      </div>
    </div>
  </div>

  <%= render 'dashboard/partials_shared/footer' %>

</div>